### ISSUE TITLE
When opening the console, it dumps a certificate and does not connect

### ISSUE THREAD

**Issue by Gjarllarhorn** [Microsoft/azserialconsole#10]
When opening the serial console, it dumps a certificate to the console and doesn't allow connections. Pressing enter does nothing, clicking out of the serial console and back has the same behavior.

![image](https://user-images.githubusercontent.com/31720971/34746691-918a1b3a-f55a-11e7-92c7-349075c6cbd3.png)

Refreshing the browser brings back the console.

**Comment by harijayms** [comment]
Thanks @Gjarllarhorn  , Can you please send a mail to azserialhelp@microsoft.com with details of your subscriptionID and resourcegroup/vmname , we can take a look.

**Comment by fnunez-msft** [comment]
Looking at our telemetry, it looks like some of our processes restarted in the middle of the first connection handshake and we're not handling recovering from that as well as we should be.  You should be able to connect now, though. Can you give it a try?

**Comment by Gjarllarhorn** [comment]
@fnunez-msft yep, after refreshing the browser I was able to connect again.
@harijayms not sure if I can reproduce it, but I'll send the info right away.

Thanks! 👍

**Comment by fnunez-msft** [comment]
Thanks for reporting! I'll close this issue, if you do hit it again please reactivate.
