### ISSUE TITLE
Serial Console IPs for DoD/USGov regions?

### ISSUE THREAD

**Issue by Esme-A** [microsoft/azserialconsole#103]
Hello, my team is looking for the Serial Console IPs for DoD/USGov regions we needs to whitelist through the firewalls. I found the json download for IPs for different DoD/USGov services here https://www.microsoft.com/en-us/download/details.aspx?id=57063 however, it doesn’t lists IPs for Serial Console. 
The online documentation only has Serial Console IPs for all regions except DoD and USGov https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-windows#use-serial-console-with-custom-boot-diagnostics-storage-account-firewall-enabled

I will really appreciate any assistance

Esy

**Comment by mbifeld** [comment]
Closing as the IPs are now listed: https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows/serial-console-windows#use-serial-console-with-custom-boot-diagnostics-storage-account-firewall-enabled.
