### ISSUE TITLE
Backspace Key in SAC 

### ISSUE THREAD

**Issue by migrande** [Microsoft/azserialconsole#11]
When launching SAC for a Windows server, launching CMD, then launching PowerShell within that CMD, the backspace key behaves oddly.  Instead of doing one character at time, it does "words" at a time as if you're holding down the ctrl key.  For example, if you have "Get-NetIPConfiguration" entered, pressing backspace one time will change that to "Get-".  I've tried relaunching the session a few times, and this seems to be consistent.

**Comment by harijayms** [comment]
Thanks @migrande  for the feedback we will take a look and get back to you.

**Comment by amitchat** [comment]
We'll investigate the issue but a workaround is to use Shift+Backspace to prevent whole worlds being deleted.

**Comment by amitchat** [comment]
This is most likely related to the ps-readline module in SAC. A workaround is to remove the PSReadLine module. Remove-Module PSReadLine will remove the PSReadLine module from the current session.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/serial-console
