### ISSUE TITLE
Copy/Paste Functionality A Bit Off

### ISSUE THREAD

**Issue by dkittell** [Microsoft/azserialconsole#14]
Issue Example 1: I've noticed that if I'm pasting a long string into the Serial Console that it doesn't accept all the characters or seems to reset the placement of the cursor during paste.

Issue Example 2: In VI or NANO pasting copied text has not worked as expected yet.

On Mac OSX Sierra in Chrome Browser with all available updates on each.

**Comment by harijayms** [comment]
Thanks @dkittell  for the feedback, we will take a look

**Comment by amitchat** [comment]
There is currently a copy paste limit of around 2048 characters per paste operation. We will investigate if we can remove or change this restriction.

**Comment by theangellmethod** [comment]
This is on Win10 in Chrome Version 68.0.3440.106.
 
If I paste something with relatively few characters (89) compared to the limit : "curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > ./microsoft-prod.list" into a fresh serial console by right clicking and pasting the console looks like this:

![image](https://user-images.githubusercontent.com/23619763/44935793-f6749c80-ad26-11e8-8ef3-2274ee331492.png)


If I have multiple lines beforehand and then try to go back, I can't see the beginning of the line and it starts deleting the output of the previous console command.  But it does seem like the characters are there (3rd screenshot where cursor is dangling).

Before:
![image](https://user-images.githubusercontent.com/23619763/44936026-fe810c00-ad27-11e8-8b9e-3876a8db5e69.png)

Fresh paste:
![image](https://user-images.githubusercontent.com/23619763/44936052-13f63600-ad28-11e8-93b5-d2820fb0d862.png)

Backspacing with dangling cursor:
![image](https://user-images.githubusercontent.com/23619763/44936070-253f4280-ad28-11e8-81f0-041b170e57c9.png)

Full backspace:
![image](https://user-images.githubusercontent.com/23619763/44936085-2ff9d780-ad28-11e8-9938-c6f9d2bb6a81.png)

**Comment by asinn826** [comment]
This is an issue inherent to a serial connection - the serial terminal is unable to tell your window size (unable to [negotiate about window size](https://www.ietf.org/rfc/rfc1073.txt), therefore no SIGWINCH) so there will be issues with text wrapping. To mitigate this I would suggest installing a package that contains `resiz`, such as `xterm`. Running `resize` should fix this issue you are seeing.
