### ISSUE TITLE
Suggestion: Add link icon to top of VM blade

### ISSUE THREAD

**Issue by nelmediamike** [microsoft/azserialconsole#15]
Once GA, it would be great to have the link icon for this feature available on the top of the VM blade like "Connect" is.

**Comment by harijayms** [comment]
Thanks @nelmediamike appreciate the feedback.

**Comment by asinn826** [comment]
Serial console now shows up as a link within the bottom half of the VM connect blade - the intent was to show that serial console exists for troubleshooting connectivity issues but SSH is most likely preferred as the main method of connecting. Closing this issue for now but feel free to reopen!

![image](https://user-images.githubusercontent.com/6633402/61064130-08e34c00-a3b6-11e9-9003-b712657d26af.png)
