### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by RoudyBob** [Microsoft/azserialconsole#18]
When attempting to access either an Ubuntu Linux VM or Windows Server 2016 VM (after enabling SAC), I receive the following error: "The serial console connection to the VM encountered an error: 'Forbidden' (403) - You do not have the required permissions to use this VM serial console"

My user has 'Owner' permissions on the VMs inherited from the subscription. VMs are in the West Central US region.

**Comment by CraigWiand** [comment]
Thank you for your interest in the Azure serial console.  We have a known issue in the service we are working on fixing which can produce this error when access is grant solely by being a service administrator. Can you take a look at my comments in issue #13 and see if it applies?

**Comment by RoudyBob** [comment]
@CraigWiand - this fixed the issue. Sorry I didn't see the other open issue before raising this one. Once I added my user as a VM Contributor, I was able to access the serial console on both VMs.

**Comment by CraigWiand** [comment]
Glad this worked around the issue.  I have proposed an update to the FAQ and will will update these issues and the FAQ when we confirm the deployed fix.

**Comment by CraigWiand** [comment]
This issue should now be corrected.  If your were experiencing this issue, feel free to remove any additional explicit permissions that were granted and retry.  

Thanks!
