### ISSUE TITLE
Serial console not working after "disk swap" operation

### ISSUE THREAD

**Issue by marinnedea** [Microsoft/azserialconsole#2]
If I have to perform any operation on a disk that means detaching the disk from the VM and attaching it back, or swapping the OS disk with another OS disk, the console will fail to connect to the VM.
Right now all this ( disk swap, disk attached to another VM, rebuild Vm from fixed OS Disk, etc) are kind of standard procedures in Azure Linux troubleshooting, and I know the serial console tries to replace all those tedious procedures. However, in case a customer builds a VM from a custom image, it will have exactly the same problem.
![image 001](https://user-images.githubusercontent.com/7581631/34519027-e1d48212-f08a-11e7-99d5-ca5e85dce2da.png)
![image 002](https://user-images.githubusercontent.com/7581631/34519029-e1fac3c8-f08a-11e7-9c5f-bf116e10d81a.png)

**Comment by harijayms** [comment]
@marinnedea  Thanks for the issue report, we appreciate the feedback. This error is known and you can address this by opening a bash cloud shell session in the portal. Simply open cloud shell 

![image](https://user-images.githubusercontent.com/13948713/34534975-337a6f0c-f075-11e7-944a-6294b374ee78.png)

Once bash session succeeds open the serial console

**Comment by marinnedea** [comment]
Indeed, this workaround helps. Thank you!
