### ISSUE TITLE
Serial console for Windows no prompt for login

### ISSUE THREAD

**Issue by antomate** [Microsoft/azserialconsole#21]
Hi,

I have no issue with linux access, but when I tried with Windows, I can see the console displayed, there are some output, but no login prompt and no input is taken (I type, but nothing happens).

I can only see the message :  ============= Microsoft Azure Heakth report.... ============

The VM is up, in West Europe, the diagnostic is enable (because apparently it is required) and I am owner of the subscription (which was enough for the console for Linux VM).

**Comment by CraigWiand** [comment]
Thanks for your interest in serial console.  You will receive this type of health content if the Windows Special Administrative Console (SAC) is not enabled.  Please take a look at [Accessing Serial Console for Windows](https://github.com/Microsoft/azserialconsole/blob/master/Azure-virtual-machine-serial-console.md#accessing-serial-console-for-windows) and ensure you have followed the steps to enable SAC.

**Comment by antomate** [comment]
Thank you for the reply which closes the issue
