### ISSUE TITLE
bootdiagnostics storage account report 404 due to "serialconsole-connectionmetadata" not found

### ISSUE THREAD

**Issue by LoganZhao** [Microsoft/azserialconsole#22]
When I configure the serial console, I found in the bootdiagnostics storage account there are a lot of 404 requests.

bootdiagnostics-serialtes-84bff47e-e7d6-46d3-9992-62ff369c267fGetBlobProperties
404

SASClientOtherError         BlobNotFound

https://westeuconsole.blob.core.windows.net/bootdiagnostics-serialtes-84bff47e-e7d6-46d3-9992-62ff369c267f/serial-test.84bff47e-e7d6-46d3-9992-62ff369c267f.serialconsole-connectionmetadata?api-version=2016-05-31&se=9999-01-01T00%3A00%3A00Z&sig=XXXXX&sk=system-1&sp=rwd&sr=c&sv=2017-04-17

but I couldnt find this serial-test.84bff47e-e7d6-46d3-9992-62ff369c267f.serialconsole-connectionmetadata in my storage account. 

there are no files which end with connectionmetadata all files end with .log or .bmp.

When they query for .log or .bmp files the request is success.

======

may I know what this connectionmetadata used for and how to prevent the 404 happened?

**Comment by amitchat** [comment]
This was an internal telemetry data which was being discussed. 

We have resolved the issue offline, so closing this thread.
