### ISSUE TITLE
serial console initial error

### ISSUE THREAD

**Issue by urinaway** [Microsoft/azserialconsole#24]
Launch azure serial console for RHEL 7.6 VM, pending 10 mins still in initial status ( ref browser Google Chrome )

![initial](https://user-images.githubusercontent.com/4621560/37163034-0fc992b8-22f7-11e8-8795-0e58120ea03e.PNG)

![initial 2](https://user-images.githubusercontent.com/4621560/37163235-89819164-22f7-11e8-8837-577bfab732aa.PNG)

**Comment by CraigWiand** [comment]
Thanks for your interest in Azure serial console!  If you press 'enter' do you see a login prompt or otherwise see that the input is making it to the VM?
(we will look into the browser error but it appears to be benign relative to serial console function)

**Comment by urinaway** [comment]
Hi,
I tried 'enter', it is working, thank you :)

I've seen the login prompt successfully. But the error console for 'binding
error' lasts.

**Comment by CraigWiand** [comment]
Great, I'm glad it worked for you.

I also wanted to thank you for reporting the 'binding error'.  It is not specifically a serial console issue, but one the Azure portal team is actively looking into.
