### ISSUE TITLE
Linux VM unable to connect to serial console

### ISSUE THREAD

**Issue by bregmike** [Microsoft/azserialconsole#26]
Hi, I have 3 OEL 7.4 vms that serial console works fine and I was able to rescue them, but this one says:

Sorry, the serial console was unable to connect to the VM because the service did not respond in a timely manner. Please retry your connection. If this issue persists please visit <https://aka.ms/seria
lconsolehelp>.
To reconnect, press "Enter".

any ideas? I tried shutting down, restarting and redeploy once already.

**Comment by amitchat** [comment]
Thank you for reporting the issue.

Can you provide details of your VM that didn't respond in a timely manner? 
This would include - Region, SubscriptionId, ResourceGroup, VMName. Please send a mail to azserialhelp@microsoft.com with these details.

We will lookup our telemetry to see if we can find an answer.

**Comment by bregmike** [comment]
It seems to be working now?

It was in Canada East.

Mike Smith
Cloud Services Architect & SDM - Corporate

Brookfield Renewable
41 Victoria, Gatineau, QC
T 819-561-8654
C 819-664-9248
Mike.smith@brookfieldrenewable.com
www.brookfieldrenewable.com<http://www.brookfieldrenewable.com/>

[logo%20300dpi_bleu_rgb]

This message, including any attachments, may contain information that is proprietary, privileged and/or confidential and is intended exclusively for the person(s) to whom it is addressed. If you are not the intended recipient or have received this message in error, please notify the sender immediately by reply email and permanently delete the original transmission from the sender, including any attachments, without making a copy.

**Comment by amitchat** [comment]
We are in the process of a worldwide rollout, so perhaps this issue was resolved due to the rollout completing in your region.

I'll close this issue since it has been resolved.

**Comment by bregmike** [comment]
Thanks!

Mike Smith
Cloud Services Architect & SDM - Corporate

Brookfield Renewable
41 Victoria, Gatineau, QC
T 819-561-8654
C 819-664-9248
Mike.smith@brookfieldrenewable.com
www.brookfieldrenewable.com<http://www.brookfieldrenewable.com/>

[logo%20300dpi_bleu_rgb]

This message, including any attachments, may contain information that is proprietary, privileged and/or confidential and is intended exclusively for the person(s) to whom it is addressed. If you are not the intended recipient or have received this message in error, please notify the sender immediately by reply email and permanently delete the original transmission from the sender, including any attachments, without making a copy.
