### ISSUE TITLE
Security Issue with multiples logon

### ISSUE THREAD

**Issue by ThierryBT** [Microsoft/azserialconsole#28]
Security Issue

I and sorry for my Funny English.
When I connect in my Azure VM (portal azure) , I use my First profile.
For exemple, User1@xxx.com
Then I start Console Serie and I connect with the admin profile of the VM.
I disconnected My User1@xxx.com profile in IE, I closed my browser and I run a new profile User2@xxx.com.
If I go to Serial Console, I do not need to reconnect. The admin profile and password is always used and I have the admin rigths with another profile.
I think it's dangerous  ;)

Regards
Thierry

**Comment by harijayms** [comment]
Thanks @ThierryBT  for the feedback. Serial console to the Azure Virtual Machine is given to only users who have VM Contributor access to the Virtual Machine, this means that they are able to create new accounts, stop the VM, read the disk, modify the disk etc. In your case both the users have such access. 

For specific mitigations you can choose to enable console timeouts in bash for your linux distribution. In case of Windows SAC automatically times out the session and asks for a password again.

**Comment by harijayms** [comment]
Its basically adding TMOUT as a setting. We can evaluate adding an autologin.sh profile with these.

**Comment by ThierryBT** [comment]
Thank you very much,
I understand, actually, the contributor role already allows administrative actions on the server. So there is no security problem.
Regards
