### ISSUE TITLE
website link doesn't fit at top of screen

### ISSUE THREAD

**Issue by Lachlan-White** [Microsoft/azserialconsole#34]
The way the console session loads in browser, means that the URL is not correctly formatted:

Website Link: http://aka.ms/windowsserialconsol

Should be: http://aka.ms/windowsserialconsole
![sac](https://user-images.githubusercontent.com/19618689/38010215-bf26299a-32a3-11e8-9234-96ed15a19365.jpg)

**Comment by harijayms** [comment]
@Lachlan-White  thanks for the feedback, we will take a look.

**Comment by Lachlan-White** [comment]
No Worries,

Loving all the features
