### ISSUE TITLE
Serial Console won't work on forced tunneling networks?

### ISSUE THREAD

**Issue by fguardabassi** [Microsoft/azserialconsole#35]
Hey All - I have a private environment that have forced tunneling enabled. I can't see why this could be an issue, but I can't connect to the serial (hit enter does nothing). Yet, when I test console on a non-forced tunneling environment, it works.

**Comment by amitchat** [comment]
When you connect, do you see the history or does it simply indicate that you need to press Enter? Also, is this for a Linux or Windows VM?

**Comment by asinn826** [comment]
Closing for now, but please feel free to reopen if you're still seeing this issue!

**Comment by fguardabassi** [comment]
Hey Alfred - it's fixed. We found the problem. Sorry about that, forgot to
reply to this thread. thanks!
