### ISSUE TITLE
Virtual machine serial console (preview)

### ISSUE THREAD

**Issue by michaelandrewhaines** [Microsoft/azserialconsole#36]
Hi,

The Virtual machine serial console (preview) is a great new feature, but does it still require and connect over IP?

How exactly does this feature work if you have no IP access?

Many thanks.

**Comment by amitchat** [comment]
The serial console feature doesn’t require network access to the virtual machine. It connects to the virtual machine over its serial port, and as long as the virtual machine is correctly configured to redirect a terminal session to the COM1 of the virtual machine, connection can be established. Most of Azure platform images are already configured to support this.

In the context of Linux these settings involve certain settings in the kernel commandline and allowing getty to create a login session on ttyS0. You can read about these settings here https://www.kernel.org/doc/html/v4.12/admin-guide/serial-console.html which illustrate the setting changes.

In the context of Windows these settings involve enabling the SAC feature on the OS which then lets the OS create a session channel on COM1 that lets one control the OS through emergency mode text terminal.

Hope this explanation is helpful.
