### ISSUE TITLE
For custom Linux images, what is the kernel config to enable serial console?

### ISSUE THREAD

**Issue by enihcam** [Microsoft/azserialconsole#37]
For custom Linux images, what is the kernel config to enable serial console?
What is the minimum requirement?

**Comment by harijayms** [comment]
Thanks @enihcam  for the feedback. ensure that you have serial console enabled https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic#general-linux-system-requirements in GRUB based on the distro ensure that getty is running in ttyS0 for login.

**Comment by enihcam** [comment]
@harijayms yes I know how to enable ttyS0 in GRUB, but for the kernel config, which flags should be enabled?

**Comment by asinn826** [comment]
@enihcam - did you get this solved? Let me know if you still have questions.

**Comment by enihcam** [comment]
@asinn826 Thanks for reply. To enable this feature, I need minimum required config flags for compiling a custom linux kernel. Can you put it into the doc? You can assume all required flags are disabled by default.

More info about kernel config:
https://linuxconfig.org/custom-kernels-in-ubuntu-debian-how-when-and-why

**Comment by asinn826** [comment]
@enihcam The way I'm interpreting your question is that you're trying to compile a custom kernel ultimately for image upload and usage in Azure, and you need to know how to configure it such that serial console works with your image. Correct me if I'm wrong.

What stage are you at in the process? I assume from the comments above you are aware that you can either pass options to the kernel 1) when building the kernel, 2) starting the kernel (via a bootloader), or 3) at runtime. 

If you wanted to pass options to the kernel to enable serial console at runtime, you can do it via the bootloader (e.g. GRUB) and pass in the parameters `console=ttyS0,115200n8 earlyprintk=ttyS0,115200 rootdelay=300`. My understanding is that passing in kernel options at runtime is the recommended way of doing this.

Is that not feasible for you, and you would prefer to pass the options in at build time? Areyou able to share any more information about your situation? That would help me understand better.

**Comment by asinn826** [comment]
@enihcam - I was digging around an Ubuntu VM on Azure, it looks like the config file is located at /boot/config-*. There are a lot of serial-related flags, some of which are:
CONFIG_MAGIC_SYSRQ_SERIAL=y
CONFIG_SERIAL_8250=y

Ultimately it might be worthwhile taking a look at the whole list of serial-related flags in the config file and seeing which ones are most relevant to your image. A min set of flags *could* be the 2 I pasted above, but I am not 100% sure.

**Comment by enihcam** [comment]
@asinn826 That's helpful. Thank you. 
Maybe you can document this in public doc?

**Comment by asinn826** [comment]
@enihcam glad to hear that helped! Adding to the docs is a good idea, I'll put it in there. Closing for now but feel free to reopen this if any more questions.
