### ISSUE TITLE
Copy & Paste results in duplicated characters

### ISSUE THREAD

**Issue by jvravensberg** [Microsoft/azserialconsole#38]
I'm using the Azure Serial Console to create a new AD Domain with PowerShell. So basically, I've opened up a CMD session and in that CMD session, I've opened a PowerShell session.

When I copy the following command into the console:
Install-windowsfeature AD-domain-services

It actually adds an extra "l" to the cmdlet, like:
Installl-windowsfeature AD-domain-services

I'm using Chrome (Version 65.0.3325.181 (Official Build) (64-bit)) with the paste functionality of Chrome. Paste as plain-text does not make any difference.

Let me know if you need more info. Happy to help!

![image](https://user-images.githubusercontent.com/14926452/38170937-edc30f40-358f-11e8-9542-2c09b484932c.png)

**Comment by harijayms** [comment]
Thanks @jvravensberg  can you please try remove-module psreadline and then try again. We are actively investigating this issue, but the above seems to have helped. 

Also can you confirm the OS version of Windows that you are using?

**Comment by jvravensberg** [comment]
Thanks for the help @harijayms! Yes, that seems to work. Of course the CMDlet colors are gone now, but that fixed the issue with the double characters:
![image](https://user-images.githubusercontent.com/14926452/38188779-afb81a28-365d-11e8-861b-e1a8b840c9ad.png)

(Typo after 'servicesf' was on purpose)

I'm using Windows 10 v1709 (16299.309).

**Comment by jaapbrasser** [comment]
You could also try using CTRL V instead of right clicking. Does that make any difference, keeping psreadline enabled?
