### ISSUE TITLE
Permissions for Custom Role

### ISSUE THREAD

**Issue by GrahamHope** [Microsoft/azserialconsole#39]
I've seen that the VM Contributor Role is required for access but can you tell me the specific permission required if I want to create a Custom Role?

**Comment by harijayms** [comment]
Thanks @GrahamHope Microsoft.Compute/virtualMachines/* for the VM and Microsoft.Storage/storageAccounts/* for the VM's  boot diagnostics storage account

**Comment by GrahamHope** [comment]
Thanks @harijayms, I am trying to lock this down to only the required permissions.  I can see that the VM Contributor role has only:
Microsoft.Storage/storageAccounts/listKeys/action
Microsoft.Storage/storageAccounts/read
So I assume they will suffice instead of 
Microsoft.Storage/storageAccounts/*

I also suspect that Microsoft.Compute/virtualMachines/delete isn't needed, do you know exactly the permissions required?  This is a good starting point though, thank you.

**Comment by asinn826** [comment]
Hi @GrahamHope - were you able to get this resolved? Let me know if you still have questions.

**Comment by asinn826** [comment]
Closing for now - feel free to reopen.
