### ISSUE TITLE
SSH Key support for serial console

### ISSUE THREAD

**Issue by mabicca** [Microsoft/azserialconsole#4]
A lot of our customers deploy VM's using SSH keys, which is the recommended, more secure way of deploying Linux workloads.

It would be really great to have a way to login in the serial console with an SSH key since every time you deploy a VM using that method, password authentication is disabled.

Not sure about how we could implement that, some cloud solutions have ways for you to add and manage SSH keys on their portals.

**Comment by johanburati** [comment]
I think it is up to the customer to set up a password for root when they set up their VM.

If they do not allow it specifically in /etc/ssh/sshd_config with the PermitRootLogin option they will not be able to log in as root using SSH, but they will be able to login as root at the console.

If they do not want to allow direct root login, they could also set up some other non-root user for console access only, add it to the sudoers and restrict SSH login for that user with the DenyUsers option.

**Comment by gossion** [comment]
+1
Our customers are running [CloudFoundry](https://www.cloudfoundry.org/) on Azure, there are bunch of VMs in a deployment created by [BOSH](http://bosh.io/docs/about.html) automatically. Based on security reason, root login is not permitted for those VM, and users need to login with different SSH keys. 
That would be great if SSH key is supported.

**Comment by asinn826** [comment]
Thanks for the suggestions and volume - this is in our backlog.

**Comment by russjury** [comment]
@mabicca - CloudShell might be what you're looking for (provides a web interface that you can SSH from to any VM).  The serial console is just that - a serial console - and isn't designed to talk SSH.

**Comment by mabicca** [comment]
@russjury yes, I understand the console is just a console :) thanks. Was just thinking about making it a step forward to help with cloud customers, some other solutions do have the option to integrate with SSH key for console access on the cloud. I'll close this one.
