### ISSUE TITLE
PowerShell-based Serial Console

### ISSUE THREAD

**Issue by Ayanmullick** [microsoft/azserialconsole#42]
There should be a Powershell version for this. The console itself should be PowerShell-based like the PowerShell Cloud Shell. It also should enable me to manage the Linux VM's thru PowerShell Core and set the Powershelll ISE context to the serial console like [this] (https://blogs.msdn.microsoft.com/powershell/2017/10/19/navigate-azure-resources-just-like-a-file-system/) or have a way to get to the 'Serial Context' thru VSC.
#6310

**Comment by harijayms** [comment]
Thanks @Ayanmullick  for the feedback, we are exploring providing a command line in our future updates which you can run from powershell.

**Comment by guillemsola** [comment]
I was able to run a powershell session creating a CMD channel from the Windows SAC

```
SAC>cmd
The Command Prompt session was successfully launched.

EVENT:   A new channel has been created.  Use "ch -?" for channel help.
Channel: Cmd0002

SAC> ch -sn Cmd0002
```

Then you get this

```
Name:                  Cmd0002
Description:           Command
Type:                  VT-UTF8
Channel GUID:          343c8d43-3e41-11e8-a943-000d3ab6b1f1
Application Type GUID: 63d02271-8aa4-11d5-bccf-00b0d014a2d0

Press <esc><tab> for next channel.
Press <esc><tab>0 to return to the SAC channel.
Use any other key to view this channel.
```

Press any key and log in

```
Please enter login credentials.
Username: vmadmin
Domain  :
Password: **************
```

And then you're running a CMD from where you can launch a powershell

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Windows\system32>powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32>
```

**Comment by asinn826** [comment]
Closing this for now - feel free to reopen.
