### ISSUE TITLE
When VM provisioning is not succeeded, automatically connect to the serial console when it succeeds

### ISSUE THREAD

**Issue by sangram-pawar** [Microsoft/azserialconsole#45]
Currently, I get the following message on the serial console when the VM provisioning is not yet succeeded.

**Access to the Azure Serial Console is in preview. For more information see <https://aka.ms/serialconsolehelp>.
Connecting to console of vm1   ■ □ □
The serial console connection to the VM encountered an error: 'Bad Request'
 (400) - Provisioning for this VM has not yet succeeded. Please ensure the VM is fully deployed and retry the serial console connection.**

The problem is, even after the provisioning is successful, the message remains there on the serial console page and the only way to get to the console is, to reload the page.

It would be nice to connect automatically to the VM serial console after successful provisioning.

**Comment by harijayms** [comment]
Thanks @sangram-pawar , we will take a look into this.

**Comment by amitchat** [comment]
We have extended the timeout for some of the provisioning cases to help with this scenario.
