### ISSUE TITLE
After disconnecting due to inactivity, reconnect with single 'Enter' key press

### ISSUE THREAD

**Issue by sangram-pawar** [Microsoft/azserialconsole#46]
Currently, if I hit "Enter" key on a timed out serial console (due to inactivity), I get the message below and I have to hit 'Enter" again to reconnect. It would be nice to establish the connection with the first key press.

**The serial console encountered the following web socket error communicating with the VM: 'error: Web socket is closed or could not be opened.'. Plese validate your network connection and retry the attempt. For more information see <https://aka.ms/serialconsolehelp>**

**The serial console connection was closed. This can occur if there was an error or another user connected to the console of this virtual machine. To reconnect, press "Enter".**

**Comment by harijayms** [comment]
Thanks @sangram-pawar  , @amitchat  can you please take a look ?

**Comment by amitchat** [comment]
We cannot reproduce this issue any more. If this still occurs, please reopen this comment or open a new one.

**Comment by alogoc** [comment]
Noticed that this happens when waagent is stopped.
