### ISSUE TITLE
No Linux grub splash screen on boot

### ISSUE THREAD

**Issue by sudsdm** [Microsoft/azserialconsole#49]
Attempting to boot into recovery mode is a lot more difficult without the normal splash screen edit facility on the Linux image string.

**Comment by simonxiaoss** [comment]
Yes, we need this feature! so that we can select recovery kernels. Thanks!

**Comment by ivanalejandro20** [comment]
it is impossible to perform any normal recovery procedure with this console , when it connects servers are already booting, even if grub time has been increased. The solution msft is providing to recover from this normal issues is to delete the machine and attach disks to another machine , fix the issue and recreate the machine. this is almost impossible in a production environment where time to troubleshoot is limited , permissions are segregated , etc.

**Comment by asinn826** [comment]
We have added some extra documentation to show steps for how to drop into GRUB and recovery mode for various distros: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/serial-console-grub-single-user-mode

Do let me know if anything is missing.
