### ISSUE TITLE
The URL short link shown points to GitHub

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/azserialconsole#51]
![image](https://user-images.githubusercontent.com/11204251/40074676-dd7f968a-583f-11e8-9b57-15055a229d32.png)

The short link showing in the output above (`http://aka.ms/windowsserialconsole`) is pointing to the GitHub view of the page and not the docs view. 

It should be pointing to this URL: `https://docs.microsoft.com/en-us/azure/virtual-machines/windows/serial-console#accessing-serial-console-for-windows`

**Comment by harijayms** [comment]
Thanks @wsmelton I fixed it
