### ISSUE TITLE
Can not access anything Serial Console.

### ISSUE THREAD

**Issue by PrHar** [Microsoft/azserialconsole#52]
After following the doc on Serial Console(https://docs.microsoft.com/en-us/azure/virtual-machines/linux/serial-console#accessing-serial-console-for-linux), I still can see only the white page and anything else. 
Please find the screenshot below:
![image](https://user-images.githubusercontent.com/38486380/40260734-179594c8-5ab1-11e8-887b-495ccb0a8acf.png)

**Comment by amitchat** [comment]
@PrHar there is a bug currently in the MPAC portal causing this issue. It will be resolved shortly. You can use the following URL to navigate to the non MPAC portal: https://portal.azure.com?feature.customportal=false and launch the UI.
