### ISSUE TITLE
Serial Console initial error - windows 2016 OS

### ISSUE THREAD

**Issue by mnvprasad** [Microsoft/azserialconsole#59]
Seeing attached message for a windows 2016 OS machine. SAC has been enabled for this virtual machine and rebooted. After a while I see SAC prompt but unable to input anything.
Virtual Machine itself is in healthy state. I am just trying to learn serial console and utilizing this healthy machine for it.

![image](https://user-images.githubusercontent.com/40706269/48974466-83767b80-f020-11e8-8fa4-f8b96a39706e.png)

**Comment by CraigWiand** [comment]
Interesting.  `KD` in the screenshot is most likely the kernel debugger.  Is the VM configured for [kernel debugging](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-null-modem-cable-connection#setting-up-the-target-computer) on the serial port?  Since the VM is healthy, can you run `bcdedit /enum` and see if it is configured with debug = Yes?

**Comment by mnvprasad** [comment]
Hello,

Thank you for your reply.
Here is the output where it shows debug=Yes for all the servers with
similar behavior.
Please advise next steps to make the serial console work.
C:\Windows\system32>bcdedit /enum

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  unknown
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
integrityservices       Enable
bootshutdowndisabled    Yes
default                 {current}
resumeobject            {c1af5c3c-30c6-11e5-98ea-edab395cc73d}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 10

Windows Boot Loader
-------------------
identifier              {current}
device                  boot
path                    \Windows\system32\winload.exe
description             Windows Server 2012 R2
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {c1af5c46-30c6-11e5-98ea-edab395cc73d}
integrityservices       Enable
recoveryenabled         No
testsigning             No
allowedinmemorysettings 0x15000075
osdevice                boot
systemroot              \Windows
resumeobject            {c1af5c3c-30c6-11e5-98ea-edab395cc73d}
nx                      OptOut
bootstatuspolicy        IgnoreAllFailures
debug                   Yes
ems                     Yes

Thanks & Regards,
Prasad M

**Comment by asinn826** [comment]
@mnvprasad - Craig and I chatted about this and it looks like your VM might be configured for kernel debugging via the serial port, hence all the text you're seeing. You can turn the output off by running `bcdedit /debug off`.

**Comment by asinn826** [comment]
Closing this issue for now but feel free to reopen if need be.
