### ISSUE TITLE
A bit broken with apt

### ISSUE THREAD

**Issue by onemoreplays** [Microsoft/azserialconsole#62]
Hello,
today I was using serial console because I'm too lazy to add new IP into the list.. I tried to install Docker but then I saw this
![image](https://user-images.githubusercontent.com/29712695/55954599-6654e900-5c5f-11e9-80bb-7bdf23b50742.png)

is that because of using new Edge or because of Serial Console?

**Comment by asinn826** [comment]
Hey @onemoreplays - Assuming you're referring to the Progress bar...I think this might be a result of the serial connection, so probably not new Edge. I'm thinking it has something to do with refresh rates and data transmission rates over the serial connection (as opposed to ssh).  It shouldn't impact the actual VM, it's just to do with how data is displayed over the connection. Does that help? Happy to continue the conversation!

**Comment by asinn826** [comment]
Closing for now - feel free to reopen at any time.
