### ISSUE TITLE
Serial Console is blank on Windows 10 VM

### ISSUE THREAD

**Issue by montebhoover** [microsoft/azserialconsole#63]
I am seeing a blank console on my Windows 10 VM:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/37886197/57143796-5ba5f380-6dc8-11e9-8b0b-7df22e2aa064.png">

So far I have gone through the following troubleshooting steps:
1. Follow steps on https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/serial-console-windows#enable-serial-console-functionality
2. Enable EMS from the Azure Portal by going to Run Command -> Enable EMS
3. Restart VM
4. Retry Serial Console, but it is still blank

From #44 it looks like another user had this issue with a Windows 10 VM.  Is Serial Console expected to be available for Windows 10 VMs?  The documentation only mentions Serial Console for Windows Server VMs. Thanks!

**Comment by asinn826** [comment]
Hey @montebhoover - unfortunately, Serial Console is not yet available for Windows 10 VMs. We are working on making this happen, so stay tuned!

**Comment by montebhoover** [comment]
Okay, thanks for that!

**Comment by Tapan1684** [comment]
IS Serial console now available on Windows 10 VM. As I still see it is not working.
