### ISSUE TITLE
Suggestion: make clear upfront that SAC is not available for client OSes

### ISSUE THREAD

**Issue by andrePKI** [microsoft/azserialconsole#64]
I had to follow quite some steps to find out that serialconsole is not supported on Windows 7 and Windows 10 VMs in Azure. The confusing part is that the serial console seems to connect, but then fails to show a prompt.
```
+-----------------------------------------------+
| Connected to the serial port of the VM.       |
| If no login prompt is displayed, press ENTER. |
+-----------------------------------------------+
```
Of course in the yellow text it is explained where to find information (aka.ms/serialconsole) but before even trying the serial console I have already taken a lot of steps in vain

**Comment by asinn826** [comment]
Thanks @andrePKI for that feedback - sorry you had to go through all the pain only to be disappointed! We'll make this more clear. 

FWIW we're working with the Windows team to make Serial Console available in Windows 10 client, so stay tuned for that!
