### ISSUE TITLE
When hitting 'Enter' the command line does not go to next line. 

### ISSUE THREAD

**Issue by lascp0** [microsoft/azserialconsole#67]
'Enter' key causes command line to go across the screen, until it wraps back around. 

When hitting 'Enter' key it should go to next line.

**Comment by asinn826** [comment]
@lascp0 - similar to your other question, can you please provide some more details? Info such as whether you were using Linux or Windows, Linux distro if you were using Serial Console on a Linux VM, and your subscription id/resource group name/vm name? Once we have that info we can look into things on our end - any details you can provide will be helpful.

**Comment by lascp0** [comment]
Hi Alfred,

This has been fixed:

The issue is due to Plymouth.

From https://wiki.ubuntu.com/Plymouth<https://urldefense.proofpoint.com/v2/url?u=https-3A__wiki.ubuntu.com_Plymouth&d=DwMGaQ&c=t5orwco8fOQDtHiseQvoFbclxkpRnkTydeMH1C7v8Dw&r=yfsyvAgdM58YYv5386LOFEErejQJP5prmXsJu4-aPB45PrPbbLPseO_Q0bySI7k3&m=mL8d9t8KrbDsREjWUc75zkZ9fu7Zwjm_18fS45nm0BM&s=Ao4gctIcut-iwoZbKB8jjOCXuhh1bFf2SdE0Yim8sJ4&e=>

Plymouth is the application which provides the graphical "splash" screen when booting and shutting down an Ubuntu system.

Note that on Ubuntu, Plymouth is considered to be the "owner" of the console device (/dev/console) so no application should attempt to modify terminal attributes for this device at boot or shutdown. That’s probably also true on SLES, which explains what you’re seeing.

We do not need to run Plymouth in Azure. You don’t need a splash screen, and Plymouth interferes with the platform ability to use the serial console.

WE checked the SLES-SAP vs. SLES-SAP-BYOS image, and it seems the difference is that the ‘plymouth’ package is only installed on the BYOS image.  We already contacted with SUSE to fix this and they’ve already acknowledged the issue.

Currently workaround:
Removing Plymouth with ‘sudo zypper remove plymouth’ or adding ‘plymouth.enable=0’ to the grub kernel command line



Pino Lascala
Server Technical Engineer (Unix)
-----------------------------------------------------
Mobile: 0402 687 927
pino.lascala@sapowernetworks.com.au<mailto:pino.lascala@sapowernetworks.com.au>
-----------------------------------------------------
1 Richmond Rd, Keswick, 5035
www.sapowernetworks.com.au<http://www.sapowernetworks.com.au/>
-----------------------------------------------------
[image001]
-----------------------------------------------------
[image002]<http://www.facebook.com/SAPowerNetworks>[image003]<https://twitter.com/SAPowerNetworks>[image004]<http://www.linkedin.com/company/sa-power-networks?trk=company_logo>[image005]<http://www.youtube.com/SAPowerNetworks>

[cid:image006.png@01D4D8AF.8A2C9140]<http://platform1.sapowernetworks.com.au/myit>
