### ISSUE TITLE
"A web page is slowing down your browser."

### ISSUE THREAD

**Issue by ghost** [microsoft/azserialconsole#69]
Suddenly the serial console keeps freezing in Firefox--it's unusable. 

I use the serial console every day and this is new, so I just thought I'd let you know if you made any changes last night they're not working.

**Comment by asinn826** [comment]
Hey @243 thanks for calling this out! I'm trying out the serial console in Firefox right now and I don't see the error you saw - "A web page is slowing down your browser". Any chance you could provide more details so I can look into it some more? I'm running Firefox Quantum 68.0 using serial console on a Debian 10 VM.

**Comment by asinn826** [comment]
Closing this issue as the user has been deleted.
