### ISSUE TITLE
Serial console dimensions

### ISSUE THREAD

**Issue by spainja** [Microsoft/azserialconsole#7]
The number of rows and columns in the serial console appears to be automatically selected when the Serial Console blade is opened. Resizing the browser window doesn't change the console dimensions. It is necessary to close and reopen the blade to do this. My feature request would be to make the console dimensions configurable per VM. Keep those dimensions as the browser window is resized. Add scroll bars to the blade if the window is too small for the configured screen dimensions. Add a buffer for lines that have scrolled off the top. Make the buffer downloadable.

Thanks for developing this. I look forward one day to being able to use a GUI application like the Hyper-V Virtual Machine Connection application to access both Windows and Linux VM consoles.

**Comment by dkittell** [comment]
Just started using Serial Console and notice this as well. For me it seems to only be an issue when I'm in NANO at the moment.

**Comment by asinn826** [comment]
With a serial console, there is no SIGWINCH signal available so there is no negotiating about window size involved ([RFC 1073](https://www.ietf.org/rfc/rfc1073.txt)). As a result the VM has no direct knowledge of your terminal's screen size. I would suggest installing a package that contains the `resize` utility, like `xterm`. Running `resize` will fix the problem.
