### ISSUE TITLE
Pressing Esc is essential for navigating e.g. Vim

### ISSUE THREAD

**Issue by LukeCarrier** [microsoft/azserialconsole#71]
Please pass through this key rather than using it to remove focus from the serial console.

:crying_cat_face:

**Comment by asinn826** [comment]
@LukeCarrier - can you provide some more details? I tried to reproduce, but I'm actually able to use the escape key to switch modes within serial console. I tried in Edge dev, Chrome, Edge, and Firefox.

**Comment by LukeCarrier** [comment]
It looks like this was been caused by the [Vimum extension](https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/) (I'm running 🦊 Firefox).

Apologies; I thought I had exempted `portal.azure.com` (props on it being fairly keyboard-navigable by default!).

**Comment by asinn826** [comment]
No worries! I'll close this for now then but feel free to reopen or create more issues.
