### ISSUE TITLE
Does not render properly in Firefox or Edge

### ISSUE THREAD

**Issue by Benjin** [microsoft/azserialconsole#73]
Firefox: ![Firefox](https://user-images.githubusercontent.com/1609827/66504282-ac0f3480-ea7d-11e9-9718-810f754b318a.png)
Edge: ![Edge](https://user-images.githubusercontent.com/1609827/66504312-b9c4ba00-ea7d-11e9-9854-352be5ff446b.png)

Expected: more than 5 lines of vertical space.

**Comment by asinn826** [comment]
Thanks for the feedback, @Benjin - we're looking into this right now!

**Comment by pflickin** [comment]
FWIW, the same thing happens on Firefox, Edge Canary, and Safari (all on OSX).

**Comment by asinn826** [comment]
We've identified the issue, have a fix, and it's rolling out. Should be in the next day or two to get the fix out.

**Comment by Benjin** [comment]
Awesome!  Love the fast response.

**Comment by jnttek** [comment]
Same happening on chrome

**Comment by asinn826** [comment]
Update - it looks like it is fixed for me in my public Azure portal, but I would love feedback as to whether you all are seeing the same!

**Comment by asinn826** [comment]
This bug should be completely fixed now. Closing this issue.
