### ISSUE TITLE
Console currently broken (blank)

### ISSUE THREAD

**Issue by sebastienros** [microsoft/azserialconsole#75]
```
Uncaught Error: The origin 'https://afd.hosting-ms.portal.azure.net' is not trusted.
    at setupParentMessage (serialTerminal.js:253)
    at HTMLDocument.<anonymous> (serialTerminal.js:1548)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)
```

Tried in Chrome and Edge.

![image](https://user-images.githubusercontent.com/1165805/68907893-34789900-06fe-11ea-9a03-80d7163f6ed2.png)

**Comment by halter73** [comment]
I'm seeing the same issue on IE 11:

![image](https://user-images.githubusercontent.com/54385/68908447-2af03080-0700-11ea-849b-739691377086.png)

**Comment by halter73** [comment]
This also only seems to be happening on ms.portal.azure.com and not the public portal.

**Comment by samueljamkhandi07** [comment]
Yes, this looks to be currently not working as expected only on the ms.portal.azure.com. You can navigate to public portal and continue using serial console https://portal.azure.com/?feature.customportal=false#home

**Comment by samueljamkhandi07** [comment]
> Yes, this looks to be currently not working as expected only on the ms.portal.azure.com. You can navigate to public portal and continue using serial console https://portal.azure.com/?feature.customportal=false#home

**This is now working**

**Comment by samueljamkhandi07** [comment]
> ```
> Uncaught Error: The origin 'https://afd.hosting-ms.portal.azure.net' is not trusted.
>     at setupParentMessage (serialTerminal.js:253)
>     at HTMLDocument.<anonymous> (serialTerminal.js:1548)
>     at j (jquery-3.1.1.min.js:2)
>     at k (jquery-3.1.1.min.js:2)
> ```
> 
> Tried in Chrome and Edge.
> 
> ![image](https://user-images.githubusercontent.com/1165805/68907893-34789900-06fe-11ea-9a03-80d7163f6ed2.png)

**This is now working**

**Comment by johanburati** [comment]
Thank you @samueljamkhandi07, I confirm the serial console is working on https://portal.azure.com

**Comment by CraigWiand** [comment]
Thanks for reporting this issue in Serial Console.  Based on the above, this should only affected MSFT employees.  We expect the issue to be addressed with our next deployment.

**Comment by CraigWiand** [comment]
Thanks again for reporting, this should be fixed now.  Please let us know if it is not the case.
