### ISSUE TITLE
Error: Bad Request

### ISSUE THREAD

**Issue by johanburati** [microsoft/azserialconsole#77]
Do you know what could be causing the following error when trying to access the **Serial Console** ?

```
Connecting to the console of test01  ▢ ▢ ■
The serial console connection to the VM encountered an error: 'Bad Request'
(400) - Badrequest
```

**Comment by asinn826** [comment]
Hey @johanburati - are you able to provide any more details on this? This isn't supposed to come up in normal operations but we can dig around our telemetry to see if there are any more details available. Your subscription id, resource group name, VM name and region would be helpful (or just the latter 3 if you don't want to share your subscription id)

**Comment by johanburati** [comment]
Hi @Alfred just sent you the details by email.

**Comment by asinn826** [comment]
@johanburati based on the email details, looks like your issue is resolved now.

In case others come and read this in the future, the issue was a malformed boot diagnostics url (missing an 's' in "https://").

**Comment by sponte** [comment]
Hello, where do you configure boot diagnostics url? I am also getting 400 Bad Request
