### ISSUE TITLE
Extra characters are getting added when pasting text to the CMD in Serial Console

### ISSUE THREAD

**Issue by shashijeevan** [microsoft/azserialconsole#78]
I have opened CMD from SAC in Azure Serial Console. I have tried to check the RDP status using this command.

reg query "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections

When I pasted this text to command prompt in Azure Serial Console, one extra character is getting added in the pasted text. This is what I see in the Serial console.

reg query "HKLM\SYSTEM\CurrrentControlSet\Control\Terminal Server" /v fDenyTSConnnections

Notice that the text 'CurrentControlSet' became 'CurrrentControlSet', that has and extra 'r' character.

This is very strange. 

Due this the command is not working and I had to type every character manually.

**Comment by asinn826** [comment]
Hi @shashijeevan - if you are running the above command in PowerShell, you can run `Remove-Module PSReadLine` to unload the PSReadLine module from your current session (this won't uninstall module).

We have made the Windows team aware of this issue as the fix would have to come from Windows.

**Comment by mattduguid** [comment]
this issue still exists ~5 years later, if I hadn't seen that we need to run the following command would have been a frustrating day removing duplicate characters 🤣 also found "paste as plain text" had a better hit rate

```powershell
Remove-Module PSReadLine 
```
