### ISSUE TITLE
Is Serial Console in US Gov yet?

### ISSUE THREAD

**Issue by asinn826** [microsoft/azserialconsole#79]
We have a limited preview available at [https://aka.ms/serialconsoleusgovpreview](https://aka.ms/serialconsoleusgovpreview). For now, Serial Console is only available in US Gov through the limited preview aka.ms link above.

This limited preview should go into full public preview in the Azure portal by mid-December, available to everyone without needing the link. Serial Console will initially only be available in non-DoD regions. DoD region availability is underway but no eta yet.

Note that based on customer feedback, Serial Console is enabled at the subscription level by default in US Gov cloud. Instructions on enabling Serial Console for your subscription are located at [https://aka.ms/serialconsoleenabledisable](https://aka.ms/serialconsoleenabledisable).

**Comment by asinn826** [comment]
As an update - we are now in full public preview in US Gov Cloud. No need for the special link above, as Serial Console is now available for anyone with a VM or VM scale set in US Gov Cloud.

**Comment by mbifeld** [comment]
Closing this issue as Serial Console is available in US Gov
