### ISSUE TITLE
on to the VM encountered an error: 'Forbidden'  

### ISSUE THREAD

**Issue by DJM0502** [microsoft/azserialconsole#80]
Hi,

try to access vm machine base on ubuntu using serial console from azure portal it is giving the below error as 

on to the VM encountered an error: 'Forbidden'
 (SubscriptionNotEnabled) - Subscription name Visual Studio Enterprise, id 6e2c01d5-71b9-4ae2-b8a5-57b015ad582f is in non-Enabled state Disabled.

can you let me know why this is not working while vm creating is in correct subscription.

Thanks
DJM

**Comment by asinn826** [comment]
Hi @DJM0502 - usually that would be a result of Serial Console being disabled for your subscription. You can follow the steps at https://aka.ms/serialconsoleenabledisable to enable your subscription for Serial Console.

**Comment by asinn826** [comment]
I am closing this one as it looks like the issue described in #83. Feel free to reopen if that's not the case.

**Comment by DJM0502** [comment]
Hi

thank you for this we will be trying this.
right now we have other backlog related to azure

Thanks
Dilip
