### ISSUE TITLE
Is not looking as it should

### ISSUE THREAD

**Issue by LuisEnMarroquin** [microsoft/azserialconsole#81]
I just run `sudo apt upgrade` on Ubuntu 18 and this is how it looks:

![image](https://user-images.githubusercontent.com/35376824/70932404-4dc37c80-1fff-11ea-9d1c-7a8036ff5739.png)

**Comment by asinn826** [comment]
Hey @LuisEnMarroquin - I would suggest quickly opening and closing Cloud Shell by using the icon on the top right of the Azure Portal, or clearing the screen with Ctrl+L.
![image](https://user-images.githubusercontent.com/6633402/70948166-b581c380-200f-11ea-870f-851ab4aa8b5b.png)

Serial as a protocol can't negotiate about window size, so sometimes display bugs like this occur. Usually forcing a resize of the screen will fix it. Another alternative is to install xterm, which gives you the `resize` command that you can run.
