### ISSUE TITLE
Console currently broken (blank)

### ISSUE THREAD

**Issue by AntonBorisovRu** [microsoft/azserialconsole#82]
```
jquery-3.1.1.min.js:2 Uncaught TypeError: Cannot read property 'clientTelemetry' of undefined
    at HTMLDocument.<anonymous> (serialTerminal.js:1076)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)
```

I have tried from Edge Beta and Google Chrome. Both have the same error.

**Comment by ArturGr** [comment]
I have this error. 30 mins ago everything worked fine. Restart dosent help. How can i fix it? I dosent change anything. Simple centos VM.

`Konsolenverbindung mit "node6" wird vorbereitet.  □ □ □
Fehler bei der Verbindung der seriellen Konsole mit der VM:
 (ConnectionFailure) – Es konnte keine Verbindung hergestellt werden. Starten Sie Cloud Shell neu, und versuchen Sie esnoch mal.`

**Comment by AntonBorisovRu** [comment]
Today I checked for updates and restarted my laptop. After that, I have got the same problem again in: Google Chrome, Edge Beta, Edge (not beta), Internet Explorer 11 and Azure Portal app.

**Comment by lavlannet** [comment]
The error occurs only when setting the Russian language in the portal settings.

**Comment by AntonBorisovRu** [comment]
@lavlannet Thanks for your advise! I tried to change language settings to English and it works. But in Russian language serial console still unavailable.

**Comment by asinn826** [comment]
Hey @AntonBorisovRu - I'm able to reproduce it as well. We have this in our backlog and we will look into this bug.

**Comment by asinn826** [comment]
I completely forgot to close this when we fixed it...this should be fixed now.
