### ISSUE TITLE
Serial Console ignoring input during grub loader

### ISSUE THREAD

**Issue by BDworak** [microsoft/azserialconsole#86]
Having issues with a VM ignoring all keyboard input during the GRUB loader stage. I have gotten the grub loader to show up and have uninstalled plymouth as recommended by the documentation. What is the next step to determine why GRUB just counts down to 0 and ignores all attempts at  "esc, up, down, left, right, enter, c, v, ^, etc."?

**Comment by asinn826** [comment]
Hey Bart, happy to dive into this a bit more. What distro are you using and what does your grub config look like?

**Comment by BDworak** [comment]
RedHat Enterprise Linux running version 7.7. I think the server was originally set up from a non-azure image since I did have to modify GRUB_CMDLINE_LINUX to actually display the grub loader in Azure Serial console. 

```
GRUB_TIMEOUT=60
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="serial console"
GRUB_CMDLINE_LINUX="console=tty1 console=ttyS0,115200n8 earlyprintk=ttyS0,115200 rootdelay=300 net.ifnames=0"
GRUB_DISABLE_RECOVERY="false"
```

Currently grub will show up, but no matter what keyboard commands are used they are all ignored. Once the OS boots, the keyboard works and I am able to login via the serial console. I have tried this in both MS Chromium Edge and in Google Chrome with the same results.

**Comment by asinn826** [comment]
Can you share your VM name, resource group name, and subscription id? Feel free to email me if you're not comfortable sharing here - I think you have my email.

**Comment by BDworak** [comment]
Emailed the details. We can continue non resource specific discussions here in case anyone runs into this in the future and finds this thread :)

**Comment by asinn826** [comment]
Brief, probably not-too-helpful update, we're still unsure as to why this is occurring, but we're still looking into it!

**Comment by asinn826** [comment]
Turns out this is an issue with RHEL. Mitigation is to add the following line into your grub config:
`GRUB_TERMINAL_INPUT="serial console"`

And then rebuild grub with 
`grub2-mkconfig -o /boot/grub2/grub.cfg` if your VM is Gen 1.

You could probably get away with just serial, but I would recommend putting both the serial and the console options in there.

**Comment by asinn826** [comment]
Alternatively, just set the GRUB_TERMINAL line to "serial console" and rebuild grub, That should work too.

**Comment by BDworak** [comment]
This worked!! Thanks Alfred!

**Comment by bj00rn** [comment]
@BDworak Can we have this documented in the official documentation? Cheers!
