### ISSUE TITLE
Serial Console is blank screen in Chrome

### ISSUE THREAD

**Issue by prdeman** [microsoft/azserialconsole#88]
The serial console comes up as a blank black screen in Chrome (86.0.4240.111). It does not display "For more information on the Azure Serial Console, see <https://aka.ms/serialconsolelinux>.
Connecting to console of <node name>". This happens on my office VPN connected Mac laptop, on my personal home Windows 10 laptop, and on my Windows 2016 Azure VM. My co-workers experience the same problem. Some co-workers report that it starts working after 10 minutes or that it works on an Azure VM, but I have not experienced this. I've also tested in Firefox, Edge and Safari. It works on all those browsers.

**Comment by kof-f** [comment]
Hey Paul,

Thanks for bringing this to our attention and sorry for the late response on this issue. We've implemented a fix for this and are now waiting for it to be deployed. I hope this helps.

**Comment by prdeman** [comment]
Thank you, Kofi.

Regards,
Paul de Man | Senior Platform Engineer
Enterprise Technology & Services | ETS
Manulife

E    paul_de_man@manulife.com
<mailto:email@manulife.com>M    416 347 0856

200 Bloor St East
Toronto, ON, Canada, M4W 1E6
Out of office: 2020-11-26 – 2020-11-27, 2020-12-18 – 2020-12-31

**Comment by kof-f** [comment]
Hey @prdeman, 

We believe this should be fixed, but we won't close this issue until we get confirmation from you that it is. Please let us know.

**Comment by prdeman** [comment]
Hi Kofi,

Works perfectly. Thanks!

Regards,
Paul de Man | Senior Platform Engineer
Enterprise Technology & Services | ETS
Manulife

E    paul_de_man@manulife.com
<mailto:email@manulife.com>M    416 347 0856

200 Bloor St East
Toronto, ON, Canada, M4W 1E6
