### ISSUE TITLE
Does enabling the Serial Console functionality for Windows Server from the Azure portal restart VM?

### ISSUE THREAD

**Issue by JoserraLopez** [microsoft/azserialconsole#91]
Hi,

I found here https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-windows
that in order to access serial console for old image VMs EMS has to be enabled.

You can enable it throgh the portal option "Enable EMS" or running some command from the VM istel

Do you now if enabling EMS from the Azure portal will restart the VMs? I guess VM has to be restarted so we can use serial console.

thanks
José

**Comment by mbifeld** [comment]
Hello, we are unfortunately unable to answer this question.  This is a question for the EMS team rather than Serial Console.
