### ISSUE TITLE
Enable serial console when using managed boot diagnostic storage account

### ISSUE THREAD

**Issue by Klaas-** [microsoft/azserialconsole#92]
Hi,
currently the serial console does not work with a managed boot diagnostics storage account. I would like to use them both together.

Greetings
Klaas

**Comment by kof-f** [comment]
Hey @Klaas- and @annerajb, I know this issue is a year old but I wanted to send an update because we are expecting to have Serial console compatibility with managed boot diagnostics storage accounts by the end of June!

**Comment by Klaas-** [comment]
@kof-f -- it now works, closing this issue
