### ISSUE TITLE
Linux VM Serial Console Error

### ISSUE THREAD

**Issue by popoolasrl** [microsoft/azserialconsole#93]
I have a Linux VM in Azure and i got this error when i tried to use Serial Console:

sorry, the serial console was unable to connect to the vm because the service did not respond in a timely manner. Please retry your connection. If this issue persists please visit <https://aka.ms/serialconsolehelp> to reconnect, press "enter"

**Comment by bj00rn** [comment]
Im experiencing this error two on one Ubuntu VM.

Connecting to others are working fine

Any pointers?
