### ISSUE TITLE
Serial console does not connect on new 2vcpu Dsv5 machine type

### ISSUE THREAD

**Issue by hofmannma** [microsoft/azserialconsole#95]
I create a debian 11 test vm from portal with a traditional v3 machine type (s, 2 vcpu, 8gb).
Serial console access works out of the box.
I create the same procedure (same VNET, same boot diag storage account ) a test vm with Dsv5 machine type and serial console tries to connect until it times out.

**Comment by bj00rn** [comment]
I am experiencing the same issue on `D16ds_v5` running Ubuntu 18.04. Resized from `D8s_v3` and now the serial console has stopped working.

![image](https://user-images.githubusercontent.com/10961167/144829710-7b5c6dae-e859-40f3-afbf-d78b0674854c.png)

```
Sorry, the serial console was unable to connect to the VM because the service did not respond in a timely manner. Please retry your connection. If this issue persists please visit <https://aka.ms/serialconsolehelp>.
To reconnect, press "Enter".
```

Size: `Standard D16ds v5 (16 vcpus, 64 GiB memory)`

```bash
$ uname -a
Linux PROD-APP01 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
```

**Comment by bj00rn** [comment]
https://github.com/microsoft/azserialconsole/issues/93

**Comment by bj00rn** [comment]
#96
