### ISSUE TITLE
Any way to disable the timeout on serial consoles?

### ISSUE THREAD

**Issue by blackburried** [microsoft/azserialconsole#97]
Serial consoles are a great way to find kernel panics that are too gruesome to make it to logs or even a video console.  But, sometimes you just need these to sit and wait... and can't hit the <CR> every few minutes to keep the serial console alive.

Anyway to get rid of the timeout?

**Comment by stevew-nec** [comment]
Did you find a way to get around the timeout ?

**Comment by stevew-nec** [comment]
Actually found it ... just set export TMOUT=xxx (seconds)
![image](https://github.com/microsoft/azserialconsole/assets/65519834/50a141a4-5194-4360-8659-b5a5e7f177a0)

**Comment by blackburried** [comment]
Nice find!Sent from my iPhoneOn May 23, 2023, at 6:50 PM, steve williams ***@***.***> wrote:﻿
Actually found it ... just set export TMOUT=xxx (seconds)

**Comment by mbifeld** [comment]
Closing as issue is resolved
